#!/bin/sh

BRANCH_NAME=$(git symbolic-ref --short HEAD)

TASK_ID=$(echo $BRANCH_NAME | grep -oE '[A-Z0-9]+-[0-9]+' | head -1)

COMMIT_MSG_FILE=$1

if [ ! -z "$TASK_ID" ]; then
  if ! grep -q "($TASK_ID)" "$COMMIT_MSG_FILE"; then
    sed -i "1s/$/ ($TASK_ID)/" "$COMMIT_MSG_FILE"
  fi
fi
